<style>
	@import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,500;0,700;1,300;1,400;1,600;1,700&display=swap');

	.card {
		margin-top: 5%;
		margin-right: 5%;
		float: right;
		width: 45%;
		border-color: #111111;
		box-shadow: 7px 7px 15px #C4D9FF;
	}

	.card-header {
		display: flex;
		justify-content: center;
		font: 500 2.0rem Montserrat;
		width: 100%;
		padding: 5%;
		background-color: #407AFF;
		color: white;
	}

	.card-text {
		font: 600 1.5rem Montserrat;
		padding-right: 15%;
		margin-right: 5%;
		margin-left: 10%;
		margin-top: 2.5%;
		margin-bottom: 5%;
	}

	.card-body {
		font: 500 1.25rem Montserrat;
	}

	#nome .Nome {
		display: flex;
		width: 80%;
		border-radius: 5px;
		height: 40px;
		margin-left: 10%;
		outline: 0;
		border-color: #111111;
	}

	#nome .Nome:hover {
		transform: scale(1.02);
		transition: 1s;
	}

	#nome .Definicao:hover {
		transform: scale(1.02);
		transition: 1s;
	}

	#nome .Data:hover {
		transform: scale(1.04);
		transition: 1s;
	}

	#nome .Definicao {
		margin-left: 10%;
		display: flex;
		border-radius: 5px;
		width: 80%;
		height: 40px;
		padding-left: 10px;
		outline: 0;
		border-color: #111111;
	}

	#nome .Data {
		font: 500 1.0rem Montserrat;
		margin-left: 10%;
		display: flex;
		border-radius: 5px;
		height: 40px;
		padding-left: 10px;
		outline: 0;
		border-color: #111111;
	}

	#nome .PrioridadeLow {
		display: inline;
		justify-content: center;
		align-items: center;
		margin-top: 5%;
		margin-left: 20%;
		cursor: pointer;
	}

	#nome .PrioridadeMedium {
		display: inline;
		justify-content: center;
		align-items: center;
		cursor: pointer;
	}

	#nome .PrioridadeHigh {
		display: inline;
		justify-content: center;
		align-items: center;
		cursor: pointer;
	}

	#nome .label-low {
		display: inline;
		justify-content: center;
		align-items: center;
		padding-left: 10px;
		padding-right: 40px;
	}

	#nome .label-medium {
		display: inline;
		justify-content: center;
		align-items: center;
		padding-left: 10px;
		padding-right: 40px;
	}

	#nome .label-high {
		display: inline;
		justify-content: center;
		align-items: center;
		padding-left: 10px;
		padding-right: 40px;
	}

	#nome .Processo {
		align-items: center;
		justify-content: center;
		display: inline;
		margin-left: 35%;
		margin-top: 40px;
		margin-bottom: 5%;
		cursor: pointer;
	}

	#nome .label-processo {
		align-items: center;
		justify-content: center;
		margin-top: 10%;
		margin-left: 5%;
		font: 700 1.25rem Montserrat;
		font-style: italic;
	}

	#nome .save-button {
		display: flex;
		justify-content: center;
		align-items: center;
		background-color: #407AFF;
		color: white;
		width: 45%;
		margin-left: 27.5%;
		margin-bottom: 5%;
		height: 50px;
		margin-top: 5%;
		border-radius: 10px;
		outline: 0;
		border: 0;
	}

	#nome .save-button:hover {
		opacity: 90%;
		cursor: pointer;
		transform: scale(1.05);
		transition: 1s;
	}

	.animation {
		margin-top: 12.5%;
		float: left;
		margin-left: 5%;
	}

	#nome .text {
		margin-left: 10%;
	}

	.modal-container {
		width: 100vw;
		height: 100vh;
		color: rgba(0, 0, 0, 5);
		position: fixed;
		top: 32.5%;
		left: 32.5%;
		z-index: 2000;
		display: none;
		justify-content: center;
		align-items: center;
	}

	.modal-gui {
		background: white;
		width: 30%;
		min-width: 400px;
		padding: 45px;
		border: 10px solid #407AFF;
		color: black;
		position: relative;
		text-align: center;
	}

	.modal-title {
		padding-top: 5%;
		font: 500 1.75rem Montserrat;
	}

	.modal-subtitle {
		font: 500 1rem Montserrat;
		padding-bottom: 5%;
	}

	.button-sn1 {
		position: relative;
		margin-bottom: 0.4%;
		margin-right: 2%;
		padding: 5%;
		width: 45%;
		background-color: #407AFF;
		color: white;
		font: 600 1rem Montserrat;
		font-style: italic;
		text-align: center;
		border-radius: 10px;
		outline: 0;
		border: 0;
	}

	.button-sn1:hover {
		opacity: 90%;
		cursor: pointer;
		color: white;
		transform: scale(1.05);
		transition: 1s;
	}

	.button-sn2 {
		position: relative;
		margin-bottom: 0.4%;
		margin-left: 2%;
		padding: 5%;
		width: 45%;
		background-color: #407AFF;
		color: white;
		border-radius: 10px;
		outline: 0;
		border: 0;
		font: 600 1rem Montserrat;
		font-style: italic;
		text-align: center;
	}

	.button-sn2:hover {
		opacity: 90%;
		color: white;
		cursor: pointer;
		transform: scale(1.05);
		transition: 1s;
	}
</style>

<section>
	<div class="animation">
		<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
		<lottie-player src="https://assets6.lottiefiles.com/packages/lf20_xRmNN8.json" background="transparent" speed="1" style="width: 550px; height: 550px;" loop autoplay></lottie-player>
	</div>
	<div class="card">
		<div class="card-header">
			Cadastrar
		</div>
		<div class="card-body">
			<!-- Formulário cadastrar as tarefas-->
			<p class="card-text"><small class="text-muted">Preencha o formulário abaixo para fazer seu cadastro</small></p>
			<form name="cadastrar" id="nome" method="POST" action="/add">
				<input type="hidden" id="id" name="id" value="<?= $this->view->taskEdit['ID'] ?? ''; ?>" />
				<!--Nome/Name-->
				<label class="text" for="Nome">Nome da tarefa<sup class="text-danger"></sup></label>
				<input class="Nome" type="text" name="Nome" id="Nome" value="<?= $this->view->taskEdit['Nome'] ?? ''; ?>" />
				<br />
				<!--Descricao/Description-->
				<label class="text" for="Definicao">Definição da tarefa<sup class="text-danger"></sup></label>
				<input class="Definicao" type="text" name="Definicao" id="Definicao" value="<?= $this->view->taskEdit['Definicao'] ?? ''; ?>" />
				<br />
				<!--Prazo/Due-->
				<label class=" text" for="Prazo">Data <sup class="text-danger"></sup></label>
				<input class="Data" type="date" name="Data" id="Data" value="<?= $this->view->taskEdit['Data'] ?? ''; ?>" />
				<br />
				<!--Prioridade/Priority-->
				<input class=" PrioridadeLow" type="radio" name="Prioridade" id="low" value="Baixa" <?= (isset($this->view->taskEdit) &&
																										$this->view->taskEdit['Prioridade'] == 'Baixa') ?
																										'checked' :
																										''; ?> />
				<label class="label-low" for="low">Baixa</label>

				<input class="PrioridadeMedium" type="radio" name="Prioridade" id="medium" value="Média" <?= (isset($this->view->taskEdit) &&
																												$this->view->taskEdit['Prioridade'] == 'Média') ?
																												'checked' :
																												''; ?> />
				<label class="label-medium" for="medium">Média</label>

				<input class="PrioridadeHigh" type="radio" name="Prioridade" id="high" value="Alta" <?= (isset($this->view->taskEdit) &&
																										$this->view->taskEdit['Prioridade'] == 'Alta') ?
																										'checked' :
																										''; ?> />
				<label class="label-high" for="high">Alta</label>
				<br />
				<!--Finalizada/Finished-->
				<input class="Processo" type="checkbox" name="Processo" id="Processo" value="1" <?= (isset($this->view->taskEdit) &&
																									$this->view->taskEdit['Processo'] == 1) ?
																									'checked' :
																									'';
																								?> />
				<label class="label-processo" for="Processo">Finalizada?</label>
				<br />
				<!--Botão Salvar-->
				<input class="save-button" type="submit" name="<?= $this->view->form->getActionButton() ?>" id="<?= $this->view->form->getActionButton() ?>" value="<?= $this->view->form->getActionButton() ?>" />
			</form>
		</div>
	</div>

</section>
<!-- Tabela com as tarefas cadastradas-->
<section>
	<style>
		.title-tarefas {
			display: flex;
			justify-content: center;
			padding-top: 10%;
			width: 100%;
			font: 700 3rem Montserrat;
		}

		.subtitle-tarefas {
			display: flex;
			justify-content: center;
			width: 100%;
			font: 500 1.25rem Montserrat;
			padding-bottom: 7.5%;
		}

		.table-responsive {
			display: flex;
			justify-content: left;
			align-items: center;
			width: 95%;
			border-radius: 5px;
			margin-left: 3%;
			margin-top: 3%;
			font: 400 1.1rem Montserrat;

		}
	</style>
	<h2 class="title-tarefas">Tarefas</h2>
	<small class="subtitle-tarefas">Abaixo, você poderá visualizar uma lista detalhada dos cadastros</small>
	<div id="table" class="table-responsive">
		<table class="table table-striped table-hover table-sm">
			<thead>
				<tr class="text-white" style="background-color:#407AFF">
					<th>Item</th>
					<th>Nome</th>
					<th>Definição</th>
					<th>Prazo</th>
					<th>Prioridade</th>
					<th>Processo</th>
					<th>Editar</th>
					<th>Apagar</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->view->taskList as $taskItem) : ?>
					<tr>
						<td><?= $taskItem['ID'] ?></td>
						<td><?= $taskItem['Nome'] ?></td>
						<td><?= $taskItem['Definicao'] ?></td>
						<td><?= $taskItem['Data'] ?></td>
						<td>
							<a href="/priority/<?= $taskItem['ID'] ?>">
								<?= $taskItem['Prioridade'] ?>
							</a>
						</td>
						<td>
							<a href="/finish/<?= $taskItem['ID'] ?>">
								<?= $taskItem['Processo'] ?>
							</a>
						</td>
						<td>
							<a href="/edit/<?= $taskItem['ID'] ?>" class="btn btn-warning">Editar</a>
						</td>
						<td>
							<a href="/delete/<?= $taskItem['ID'] ?>" class="btn btn-danger btn-sm" data-confirm="Você tem certeza que deseja apagar o item selecionado?" id="clickroute">
								Apagar
							</a>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
		<a class="btn btn-info text-white" href="/index/notFinished">Exibir só as em aberto</a>
				<a class="btn btn-info text-white" href="/index/all">Exibir Todas</a>
		<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLabel">Apagar Item</h5><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					</div>
					<div class="modal-body" id="modal-body"></div>
					<div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><a class="btn btn-danger text-white" id="dataConfirmOK">Apagar</a></div>
				</div>
			</div>
		</div>
</section>

</html>