<style>
	.card {
		margin-left: 3%;
		margin-top: 3%;
		float: left;
		width: 45%;
		display: flex;
		border-color: #111111;
		box-shadow: 7px 7px 15px #C4D9FF;
	}

	.card-header {
		font: 700 2.0rem Montserrat;
		width: 100%;
		padding: 5%;
		background-color: #407AFF;
		color: white;
	}

	.card-text {
		margin-left: 10%;
	}

	#nome .Nome {
		display: flex;
		width: 80%;
		border-radius: 10px;
		height: 40px;
		margin-left: 10%;
		outline: 0;
		border-color: #111111;
	}

	#nome .Nome:hover {
		transform: scale(1.02);
		transition: 1s;
	}

	#nome .Definicao:hover {
		transform: scale(1.02);
		transition: 1s;
	}

	#nome .Data:hover {
		transform: scale(1.04);
		transition: 1s;
	}

	#nome .Definicao {
		margin-left: 10%;
		display: flex;
		border-radius: 10px;
		width: 80%;
		height: 40px;
		padding-left: 10px;
		outline: 0;
		border-color: #111111;
	}

	#nome .Data {
		margin-left: 10%;
		display: flex;
		border-radius: 10px;
		height: 40px;
		padding-left: 10px;
		outline: 0;
		border-color: #111111;
	}

	#nome .PrioridadeLow {
		margin-left: 10%;
		cursor: pointer;
	}

	#nome .PrioridadeMedium {
		cursor: pointer;
	}

	#nome .PrioridadeHigh {
		cursor: pointer;
	}

	#nome .label-low {
		padding-left: 10px;
		padding-right: 40px;
	}

	#nome .label-medium {
		padding-left: 10px;
		padding-right: 40px;
	}

	#nome .label-high {
		padding-left: 10px;
		padding-right: 40px;
	}

	#nome .Processo {
		margin-left: 30%;
		margin-top: 40px;
		margin-bottom: 40px;
		cursor: pointer;
	}

	#nome .label-processo {
		margin-top: 10px;
		padding-left: 10px;
		padding-right: 20px;
		font-weight: 40px;
		font: 700 1.5rem Montserrat;
	}

	#nome .save-button {
		float: right;
		background-color: #407AFF;
		color: white;
		width: 35%;
		margin-right: 10%;
		height: 45px;
		margin-top: 10px;
		border-radius: 10px;
		outline: 0;
		border: 0;
	}

	#nome .save-button:hover {
		opacity: 90%;
		cursor: pointer;
		transform: scale(1.05);
		transition: 1s;
	}

	#nome .update-button {
		float: left;
		background-color: #407AFF;
		color: white;
		width: 35%;
		height: 45px;
		margin-top: 10px;
		margin-left: 10%;
		border-radius: 10px;
		margin-bottom: 10%;
		outline: 0;
		border: 0;
	}

	#nome .update-button:hover {
		opacity: 90%;
		cursor: pointer;
		transform: scale(1.05);
		transition: 1s;
	}

	.animation {
		float: right;
		margin-right: 3%;
	}

	#nome .text {
		margin-left: 10%;
	}
</style>

<section>
	<div class="animation">
		<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
		<lottie-player src="https://assets6.lottiefiles.com/packages/lf20_xRmNN8.json" background="transparent" speed="1" style="width: 600px; height: 600px;" loop autoplay></lottie-player>
	</div>
	<div class="card">
		<div class="card-header">
			Cadastrar
		</div>
		<div class="card-body">
			<!-- Formulário cadastrar as tarefas-->
			<p class="card-text"><small class="text-muted">Preencha o formulário abaixo para fazer seu cadastro</small></p>
			<form name="cadastrar" id="nome" method="POST" action="/add">
				<!--Nome/Name-->
				<label class="text" for="Nome">Nome da tarefa<sup class="text-danger"></sup></label>
				<input class="Nome" type="text" name="Nome" id="Nome" required />
				<br />
				<!--Descricao/Description-->
				<label class="text" for="Definicao">Definição da tarefa<sup class="text-danger"></sup></label>
				<input class="Definicao" type="text" name="Definicao" id="Definicao" required />
				<br />
				<!--Prazo/Due-->
				<label class="text" for="Prazo">Data <sup class="text-danger"></sup></label>
				<input class="Data" type="date" name="Data" id="Data" required />
				<br />
				<!--Prioridade/Priority-->
				<input class="PrioridadeLow" type="radio" name="Prioridade" id="low" value="Baixa" />
				<label class="label-low" for="low">Baixa</label>

				<input class="PrioridadeMedium" type="radio" name="Prioridade" id="medium" value="Média" />
				<label class="label-medium" for="medium">Média</label>

				<input class="PrioridadeHigh" type="radio" name="Prioridade" id="high" value="Alta" />
				<label class="label-high" for="high">Alta</label>
				<br />
				<!--Finalizada/Finished-->
				<input class="Processo" type="checkbox" name="Processo" id="Processo" value="Finalizada" />
				<label class="label-processo" for="Processo">Finalizada?</label>
				<br />
				<!--Botão Alterar-->
				<input class="update-button" type="submit" name="Alterar" id="Alterar" value="Alterar" />
				<!--Botão Salvar-->
				<input class="save-button" type="submit" name="Salvar" id="Salvar" value="Salvar" />
			</form>
		</div>
	</div>

</section>
<!-- Tabela com as tarefas cadastradas-->
<section>
	<style>
		.title-tarefas {
			display: flex;
			justify-content: left;
			width: 100%;
			margin-left: 3%;
			padding-top: 3%;
		}

		.subtitle-tarefas {
			display: flex;
			justify-content: left;
			width: 100%;
			margin-left: 3%;
		}

		.table-responsive{
			display: flex;
			justify-content: left;
			width: 95%;
			margin-left: 3%;
			margin-top: 3%;
			font: 700 1.0rem Montserrat;

		}
	</style>
	<h2 class="title-tarefas">Tarefas</h2>
	<small class="subtitle-tarefas">Abaixo, você poderá visualizar uma lista detalhada dos cadastros</small>
	<div class="table-responsive">
		<table class="table table-hover table-sm">
			<thead>
				<tr>
					<th>Item</th>
					<th>Nome</th>
					<th>Definição</th>
					<th>Prazo</th>
					<th>Prioridade</th>
					<th>Processo</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->view->taskList as $taskItem) : ?>
					<tr>
						<td><?= $taskItem['ID'] ?></td>
						<td><?= $taskItem['Nome'] ?></td>
						<td><?= $taskItem['Definicao'] ?></td>
						<td><?= $taskItem['Data'] ?></td>
						<td><?= $taskItem['Prioridade'] ?></td>
						<td><?= $taskItem['Processo'] ?></td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</section>

</html>