<style>
    @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,500;0,700;1,300;1,400;1,600;1,700&display=swap');

    .card {
        margin-top: 5%;
        margin-left: 5%;
        margin-bottom: 5%;
        float: left;
        width: 45%;
        border-color: #111111;
        box-shadow: 7px 7px 15px #C4D9FF;
    }

    .card-header {
        display: flex;
        justify-content: center;
        font: 500 2.0rem Montserrat;
        width: 100%;
        padding: 5%;
        background-color: #407AFF;
        color: white;
    }

    .card-text {
        font: 600 1.5rem Montserrat;
        padding-right: 15%;
        margin-right: 5%;
        margin-left: 10%;
        margin-top: 2.5%;
        margin-bottom: 5%;
    }

    .card-body {
        font: 500 1.25rem Montserrat;
    }

    #nome .Nome {
        display: flex;
        width: 80%;
        border-radius: 5px;
        height: 40px;
        margin-left: 10%;
        outline: 0;
        border-color: #111111;
    }

    #nome .Nome:hover {
        transform: scale(1.02);
        transition: 1s;
    }

    #nome .Definicao:hover {
        transform: scale(1.02);
        transition: 1s;
    }

    #nome .Data:hover {
        transform: scale(1.04);
        transition: 1s;
    }

    #nome .Definicao {
        margin-left: 10%;
        display: flex;
        border-radius: 5px;
        width: 80%;
        height: 40px;
        padding-left: 10px;
        outline: 0;
        border-color: #111111;
    }

    #nome .Data {
        font: 500 1.0rem Montserrat;
        margin-left: 10%;
        display: flex;
        border-radius: 5px;
        height: 40px;
        padding-left: 10px;
        outline: 0;
        border-color: #111111;
    }

    #nome .PrioridadeLow {
        display: inline;
        justify-content: center;
        align-items: center;
        margin-top: 5%;
        margin-left: 20%;
        cursor: pointer;
    }

    #nome .PrioridadeMedium {
        display: inline;
        justify-content: center;
        align-items: center;
        cursor: pointer;
    }

    #nome .PrioridadeHigh {
        display: inline;
        justify-content: center;
        align-items: center;
        cursor: pointer;
    }

    #nome .label-low {
        display: inline;
        justify-content: center;
        align-items: center;
        padding-left: 10px;
        padding-right: 40px;
    }

    #nome .label-medium {
        display: inline;
        justify-content: center;
        align-items: center;
        padding-left: 10px;
        padding-right: 40px;
    }

    #nome .label-high {
        display: inline;
        justify-content: center;
        align-items: center;
        padding-left: 10px;
        padding-right: 40px;
    }

    #nome .Processo {
        align-items: center;
        justify-content: center;
        display: inline;
        margin-left: 35%;
        margin-top: 40px;
        margin-bottom: 5%;
        cursor: pointer;
    }

    #nome .label-processo {
        align-items: center;
        justify-content: center;
        margin-top: 10%;
        margin-left: 5%;
        font: 700 1.25rem Montserrat;
        font-style: italic;
    }

    #nome .save-button {
        display: flex;
        justify-content: center;
        align-items: center;
        background-color: #407AFF;
        color: white;
        width: 45%;
        margin-left: 27.5%;
        margin-bottom: 5%;
        height: 50px;
        margin-top: 5%;
        border-radius: 10px;
        outline: 0;
        border: 0;
    }

    #nome .save-button:hover {
        opacity: 90%;
        cursor: pointer;
        transform: scale(1.05);
        transition: 1s;
    }

    .animation {
        margin-top: 12.5%;
        float: right;
        margin-right: 5%;
    }

    #nome .text {
        margin-left: 10%;
    }
</style>

<section>
    <div class="animation">
        <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
        <lottie-player src="https://assets9.lottiefiles.com/packages/lf20_sxrbhrtx.json" background="transparent" speed="1" style="width: 550px; height: 550px;" loop autoplay></lottie-player>
    </div>
    <div class="card">
        <div class="card-header">
            Editar Cadastros
        </div>
        <div class="card-body">
            <!-- Formulário cadastrar as tarefas-->
            <p class="card-text"><small class="text-muted">Preencha o formulário abaixo para fazer a edição de seu cadastro</small></p>
            <form id="nome" method="POST" action="<?= $this->view->form->getAction() ?>">
                <!--ID/id-->
                <input type="hidden" id="id" name="id" value="<?= $this->view->taskEdit['ID'] ?? ''; ?>" />
                <!--Nome/Name-->
                <label class="text" for="Nome">Nome da tarefa<sup class="text-danger"></sup></label>
                <input class="Nome" type="text" name="Nome" id="Nome" value="<?= $this->view->taskEdit['Nome'] ?? ''; ?>" />
                <br />
                <!--Descricao/Description-->
                <label class="text" for="Definicao">Definição da tarefa<sup class="text-danger"></sup></label>
                <input class="Definicao" type="text" name="Definicao" id="Definicao" value="<?= $this->view->taskEdit['Definicao'] ?? ''; ?>" />
                <br />
                <!--Prazo/Due-->
                <label class=" text" for="Prazo">Data <sup class="text-danger"></sup></label>
                <input class="Data" type="date" name="Data" id="Data" value="<?= $this->view->taskEdit['Data'] ?? ''; ?>" />
                <br />
                <!--Prioridade/Priority-->
                <input class=" PrioridadeLow" type="radio" name="Prioridade" id="low" value="Baixa" <?= (isset($this->view->taskEdit) &&
                                                                                                        $this->view->taskEdit['Prioridade'] == 'Baixa') ?
                                                                                                        'checked' :
                                                                                                        ''; ?> />
                <label class="label-low" for="low">Baixa</label>

                <input class="PrioridadeMedium" type="radio" name="Prioridade" id="medium" value="Média" <?= (isset($this->view->taskEdit) &&
                                                                                                                $this->view->taskEdit['Prioridade'] == 'Média') ?
                                                                                                                'checked' :
                                                                                                                ''; ?> />
                <label class="label-medium" for="medium">Média</label>

                <input class="PrioridadeHigh" type="radio" name="Prioridade" id="high" value="Alta" <?= (isset($this->view->taskEdit) &&
                                                                                                        $this->view->taskEdit['Prioridade'] == 'Alta') ?
                                                                                                        'checked' :
                                                                                                        ''; ?> />
                <label class="label-high" for="high">Alta</label>
                <br />
                <!--Finalizada/Finished-->
                <input class="Processo" type="checkbox" name="Processo" id="Processo" value="1" <?= (isset($this->view->taskEdit) &&
                                                                                                                $this->view->taskEdit['Processo'] == 1) ?
                                                                                                                'checked' :
                                                                                                                '';
                                                                                                            ?> />
                <label class="label-processo" for="Processo">Finalizada?</label>
                <br />
                <!--Botão Salvar-->
                <input class="save-button" type="submit" name="<?= $this->view->form->getActionButton() ?>" id="<?= $this->view->form->getActionButton() ?>" value="<?= $this->view->form->getActionButtonText() ?>" />
            </form>
        </div>
    </div>