<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="description" content="Sistema Gerenciador de Tarefas">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,500;0,700;1,300;1,400;1,600;1,700&display=swap" rel="stylesheet">
	<title>Gerenciador</title>
</head>

<style>
	body {
		font-family: 'Montserrat', sans-serif;
	}

	.navbar {
		position: center;
		margin-bottom: 0.4%;
		padding: 2%;
		background-color: #407AFF;
		color: white;
		font: 600 1.5rem Montserrat;
		font-style: italic;
	}

	.navbar .text {
		color: white;
	}

	.navbar .text:hover {
		color: white;
		transform: scale(1.03);
		transition: 0.5s;
	}

	.alert {
		margin-left: 49.5%;
		width: 49.5%;
		margin-top: 10px;
	}
</style>

<body>
	<nav class="navbar">
		<a class="text" href="\">Gerenciador de Tarefas</a>
	</nav>
	<!--messages-->
	<?php if (isset($this->view->result)) : ?>
		<?php if ($this->view->result == 'ADD_OK') : ?>
			<div class="alert alert-success" role="alert">
				Tarefa adicionada com sucesso!
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		<?php elseif ($this->view->result == 'ADD_ERROR') : ?>
			<div class="alert alert-danger" role="alert">
				Erro ao adicionar tarefa!
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			<?php elseif ($this->view->result == 'EDIT_OK') : ?>
				<div class="alert alert-success" role="alert">
					Tarefa atualizada com sucesso!
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
			<?php elseif ($this->view->result == 'EDIT_ERROR') : ?>
				<div class="alert alert-danger" role="alert">
					A tarefa não foi editada pois não sofreu nenhuma alteração!
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
			<?php elseif ($this->view->result == 'DELETE_OK') : ?>
				<div class="alert alert-success" role="alert">
					Tarefa deletada com sucesso!
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
			<?php elseif ($this->view->result == 'DELETE_ERROR') : ?>
				<div class="alert alert-danger" role="alert">
					Erro ao deletar tarefa!
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
			<?php endif ?>
		<?php endif ?>
		<?= $this->content() ?>
</body>
<footer>
	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="/index/script.js"></script>
</footer>

</html>