<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="description" content="Sistema Gerenciador de Tarefas">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@1,600&display=swap" rel="stylesheet">
	<title>Gerenciador de Tarefas</title>
</head>

<style>
	body {
		font-family: 'Montserrat', sans-serif;
	}

	.navbar-brand {
		display: flex;
		justify-content: left;
		text-align: left;
		width: 100%;
		position: center;
		margin-top: 0.4%;
		margin-bottom: 0.4%;
	}

	.alert {
		margin-left: 49.5%;
		width: 49.5%;
		margin-top: 10px;
	}

</style>

<body>
	<nav class="navbar navbar-dark bg-primary">
		<a class="navbar-brand" href="\">Gerenciador de Tarefas</a>
	</nav>
	<!--messages-->
	<?php if (isset($this->view->result)) : ?>
		<?php if ($this->view->result == 'ADD_OK') : ?>
			<div class="alert alert-success" role="alert">
				Tarefa adicionada com sucesso!
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		<?php elseif ($this->view->result == 'ADD_ERROR') : ?>
			<div class="alert alert-danger" role="alert">
				Erro ao adicionar tarefa!
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		<?php endif ?>
	<?php endif ?>
	<?= $this->content() ?>
</body>
<footer>
	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</footer>

</html>